/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Loginnew.java
 *
 * Created on Mar 31, 2013, 2:27:27 PM
 */

package cancer;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Seban
 */
public class Loginnew extends javax.swing.JFrame {

    /** Creates new form Loginnew */
    public Loginnew() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel2.setText("UserName");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 230, 55, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 280, 48, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancer/login.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 330, 80, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancer/register.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 330, 80, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(430, 220, 140, 30);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 3, 36));
        jLabel1.setText("Cancer Gene Detection");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 370, 50);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(430, 270, 140, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancer/God is always on time.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 570);

        setBounds(300, 100, 617, 611);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String u=jTextField1.getText();
        String p=jPasswordField1.getText();
        if(u.equals(""))
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Username Empty!!");
        }
        else if(p.equals(""))
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Password Empty!!");
        }
        else
        {
            if(u.equals("admin")&&p.equals(""))
            {
                
            }
            else
            {
                Dbconnect obj=new Dbconnect();
                java.sql.ResultSet rs=obj.check(u, p);
                try
                {
                    if (rs.next())
                    {
                        dispose();
                        new UserProfileNew().setVisible(true);
                    }
                    else
                    {
                        javax.swing.JOptionPane.showMessageDialog(null, "Invalid Login!!");
                    }
                }
                catch (SQLException ex)
                {
                    Logger.getLogger(Loginnew.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new RegisterNew().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
             // TODO add your handling code here:
        

    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginnew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
